<?php /** @var $block \Magenest\PromotionPopup\Block\PromotionPopup */
$configValue = $block->getConfigValue(); ?>
<?php if ($block->isValidToDisplay($configValue['customer_group'], $configValue['status'])): ?>
    <div class="magenest-promotion-popup-wrapper" id="magenest-promotion-popup">
        <div class="magenest-popup-container">
            <div class="magenest-popup-notification" id="magenest-popup-notification">
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
        "*": {
            "magenestPromotionPopup" : {
                "notification" : "<?= $block->escapeHtml($configValue['notification']); ?>"
            }
        }
    }
    </script>
<?php endif; ?>
