<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<legend class="legend"><span><?= $block->escapeHtml(__('Additional Information')) ?></span></legend><br>
<div class="field phone_number">
    <label class="label" for="phone_number">
        <span><?= $block->escapeHtml(__('Phone number')) ?></span>
    </label>
    <div class="control" data-mage-init='{"customValidateMagenest": {}}'>
        <input type="text"
               name="phone_number"
               id="phone_number"
               value=""
               title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>"
               class="input-text"
               data-validate='{"custom-validate-phone-number":true}'
               maxlength="14">
    </div>
</div>
